import json
import random
import re

entries = [
    ('Gaggan Anand', '亚洲前50餐厅，现代印度创意料理', '68/1 Soi Langsuan, Lumpini', 'Lumpini'),
    ('Sühring', '米其林双星，德国风味现代料理', '10 Yen Akat Soi 3, Chong Nonsi', 'Chong Nonsi'),
    ('Le Du', '当代泰式料理与本地季节食材', '399/3 Silom Soi 7, Silom', 'Silom'),
    ('Nahm', '米其林推荐经典泰国风味', '27 S Sathorn Rd, Sathorn', 'Sathorn'),
    ('Sorn', '米其林二星南部泰式料理', '56 Sukhumvit 26, Khlong Tan', 'Sukhumvit 26'),
    ('Paste', '亚洲前50餐厅，皇室泰式新潮美食', '3/1 Soi Tantawan, Lumpini', 'Lumpini'),
    ('Jay Fai', '米其林一星街头海鲜煎蛋', '327 Maha Chai Rd, Samran Rat', 'Samran Rat'),
    ('Bo.lan', '传统泰式烹饪与有机菜园', '24 Sukhumvit 53, Phra Khanong', 'Phra Khanong'),
    ('80/20', '本地食材与轻奢风味', '72/1 Sukhumvit 61 Lane 1, Phra Khanong', 'Phra Khanong'),
    ('Canvas', '现代泰式料理与艺术呈盘', '8/8 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Aksorn', '米其林推荐经典泰式家常菜', '45 Sukhumvit 23, Khlong Toei', 'Sukhumvit 23'),
    ('Saneh Jaan', '传统泰式名厨私房料理', '26 Sukhumvit 23, Khlong Toei', 'Sukhumvit 23'),
    ('Elements', '米其林三星主厨新派泰料理', '42 Sukhumvit 26, Khlong Tan', 'Sukhumvit 26'),
    ('Le Normandie', '老牌法式美馔与河畔华丽氛围', '48 Oriental Ave, Riverside', 'Riverside'),
    ('Aaharn', '现代泰式多道套餐体验', '80/1 Sukhumvit 53, Phra Khanong', 'Phra Khanong'),
    ('Savelberg Bangkok', '荷式经典与泰式食材混搭', '37/1 Langsuan Rd, Pathum Wan', 'Langsuan'),
    ('Issaya Siamese Club', '名厨 Pailin 的泰式创意料理', '4 Sri Aksorn Rd, Langsuan', 'Langsuan'),
    ('Bunker', '美式料理与工业风酒吧', '50 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Dala', '法式料理与繁华城市绿洲', '152/3 Ploenchit Rd, Ploenchit', 'Ploenchit'),
    ('Babette\'s The Steakhouse', '精品牛排与经典西餐', '57 Sukhumvit 39, Phrom Phong', 'Phrom Phong'),
    ('The Bamboo Bar', '曼谷最经典的酒店鸡尾酒吧', 'Mandarin Oriental, Riverside', 'Riverside'),
    ('Tropic City', '亚洲前50酒吧，热带风味鸡尾酒', '672/71 Charoenkrung Rd, Charoenkrung', 'Charoenkrung'),
    ('Teens of Thailand', '经典琴通纳那巷的特色鸡尾酒', '76 Soi Nana, Chinatown', 'Chinatown'),
    ('Backstage Cocktail Bar', '表演主题调酒吧', '6 Sukhumvit 23, Asoke', 'Asoke'),
    ('Rabbit Hole', '隐秘酒吧与创意调酒', '116/2 Thonglor 13, Thonglor', 'Thonglor'),
    ('Iron Balls Distillery', '工业风烈酒与手调鸡尾酒', '30 Sukhumvit 26, Khlong Tan', 'Sukhumvit 26'),
    ('Vesper', '现代欧风酒吧餐厅', '10 Convent Rd, Silom', 'Silom'),
    ('Asia Today', '香料主题小酒吧', '189/4 Charoen Krung 24, Chinatown', 'Charoenkrung'),
    ('Smalls', '舒适老洋房风情的地下酒吧', '186/3 Suan Phlu, Sathorn', 'Suan Phlu'),
    ('J.Boroski', '私人订制鸡尾酒体验', '3/1 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('TEP BAR', '经典泰式风味调酒与传统表演', '69/9 Soi Nana, Chinatown', 'Chinatown'),
    ('The Locker Room', '秘密酒吧与运动主题调酒', '7/1 Sukhumvit 31, Phrom Phong', 'Sukhumvit 31'),
    ('The House on Sathorn', '历史建筑里的酒吧餐厅', '106 North Sathorn Rd, Sathorn', 'Sathorn'),
    ('The Bar Upstairs', '屋顶酒吧与城市夜景', '49/2 Soi Ruamrudee, Lumphini', 'Sathorn'),
    ('Sky Bar Lebua', '高空夜景与经典鸡尾酒', '1055 Silom Rd, Silom', 'Silom'),
    ('Moon Bar', '高空屋顶酒吧俯瞰湄南河', '21/100 South Sathon Rd, Sathorn', 'Sathorn'),
    ('Octave Rooftop Lounge', '360 度天台派对酒吧', '2 Sukhumvit 57, Thonglor', 'Thonglor'),
    ('Above Eleven', '秘鲁日式融合屋顶酒吧', '38/8 Sukhumvit 11, Nana', 'Sukhumvit 11'),
    ('Vertigo Too', '双层屋顶酒吧与城市天际线', '12/52 South Sathon Rd, Sathorn', 'Sathorn'),
    ('HI-SO Bar', '豪华酒店顶部休闲酒吧', '2 North Sathorn Rd, Sathorn', 'Sathorn'),
    ('Mahanakhon SkyBar', '泰国最高观景酒吧', '114 Naradhiwas Rajanagarindra Rd, Silom', 'Silom'),
    ('Scarlett Wine Bar', '红酒与城市天际观景', '37-37/1 Patpong 2, Silom', 'Silom'),
    ('ThreeSixty Rooftop Bar', '全景露台酒吧与夜景', '40/5 Surawong Rd, Silom', 'Silom'),
    ('Red Sky', '大型屋顶酒吧与法式餐点', '999/99 Rama I Rd, Pathum Wan', 'Pathum Wan'),
    ('CÉ LA VI', '亚洲前50酒吧之一的高端天台', '39/8-9 Sathorn Rd, Sathorn', 'Sathorn'),
    ('Mikkeller Bangkok', '精酿啤酒酒吧与潮流氛围', '38 Sukhumvit 26, Khlong Tan', 'Sukhumvit 26'),
    ('Iron Fairies', '梦幻铁艺主题酒吧', '464/1-5 Thonglor 10, Thonglor', 'Thonglor'),
    ('Q Bar', '经典夜店与国际调酒', '44/5 Sukhumvit 11, Nana', 'Sukhumvit 11'),
    ('Hair of the Dog', '美式酒吧与独特鸡尾酒', '170/1 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Forbidden City', '老牌中式风格酒吧', '29/3-4 Soi Ruamrudee, Lumphini', 'Sathorn'),
    ('The Speakeasy', '复古风格的隐秘屋顶酒吧', '939/39 Rama I Rd, Pathum Wan', 'Pathum Wan'),
    ('Hemingway\'s Bangkok', '晚宴式酒吧与经典鸡尾酒', '1 Sukhumvit 11, Nana', 'Sukhumvit 11'),
    ('L\'Atelier de Joël Robuchon', '名厨法国料理餐酒体验', '39/1-2 Sathorn Rd, Sathorn', 'Sathorn'),
    ('Maison Jean Philippe', '法式甜点与咖啡轻食', '5/F EmQuartier, Phrom Phong', 'Phrom Phong'),
    ('Roast', '精品咖啡与全天早午餐', '49/2 The Commons, Thonglor', 'Thonglor'),
    ('Casa Lapin', '复古风格精品咖啡馆', '16 Sukhumvit 49, Phrom Phong', 'Phrom Phong'),
    ('One Ounce for Onion', '亚洲前50咖啡馆与手冲精品', '98/1 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Toby\'s', '澳式早午餐与手冲咖啡', '36 Soi Sukhumvit 38, Phrom Phong', 'Phrom Phong'),
    ('Roots Handmade Coffee', '本地烘焙与咖啡实验室', '37/1 Sukhumvit 49, Phrom Phong', 'Phrom Phong'),
    ('Café Tartine', '法式甜点与温馨咖啡时光', '29 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Audrey Café', '网红泰式西式混搭甜点', '4 Siam Square Soi 3, Pathum Wan', 'Pathum Wan'),
    ('After You Dessert Cafe', '甜点连锁招牌蜜糖吐司', 'Siam Square One, Pathum Wan', 'Pathum Wan'),
    ('Mont Nom Sod', '经典泰式牛奶吐司与甜品', '2/1 Sukhumvit Soi 21, Asoke', 'Asoke'),
    ('Mae Varee Mango Sticky Rice', '知名芒果糯米饭老店', '16 Ari Samphan Soi 1, Ari', 'Ari'),
    ('Coffee Beans by Dao', '简约文青风咖啡馆', '14 Sukhumvit 49, Phrom Phong', 'Phrom Phong'),
    ('Gallery Drip Coffee', '画廊主题手冲精品咖啡', 'Soi Ari 5, Ari', 'Ari'),
    ('Rocket Coffeebar', '北欧风格咖啡与早午餐', 'Soi Sukhumvit 49, Phrom Phong', 'Phrom Phong'),
    ('FABB Coffee Roasters', '咖啡烘焙与单品手冲', 'Sukhumvit 49 Alley 1, Phrom Phong', 'Phrom Phong'),
    ('Hands and Heart Bakery', '手工面包与精品咖啡', 'Udomsuk 36, Bang Na', 'Bang Na'),
    ('Café Chilli White', '泰式甜品与网红奶茶', 'Soi Ari 4, Ari', 'Ari'),
    ('The Never Ending Summer', '河畔风格泰式餐厅与甜点', '41/5 Charoenkrung Rd, Charoenkrung', 'Charoenkrung'),
    ('Namsaah Bottling Trust', '复古粉红泰式料理与酒吧', '78/4-5 Convent Rd, Silom', 'Silom'),
    ('Eat Me', '国际风味与现代美学餐厅', '20 Sathorn Soi 11, Sathorn', 'Sathorn'),
    ('Blue Elephant', '经典泰式名厨餐厅', '233 S Sathorn Rd, Sathorn', 'Sathorn'),
    ('Baan Khanitha', '泰式家常与古典餐饮', '36/1 Sukhumvit 23, Khlong Toei', 'Sukhumvit 23'),
    ('Thip Samai', '米其林必比登老牌泰式炒河粉', '313 Maha Chai Rd, Samran Rat', 'Samran Rat'),
    ('Somtum Der', '黑珍珠青木瓜沙拉名店', '5 Ekamai 10, Phra Khanong', 'Phra Khanong'),
    ('Krua Apsorn', '家庭式泰国家常菜', '169 Dinso Rd, Phra Nakhon', 'Phra Nakhon'),
    ('Baan Ice Rice', '街头经典冰糯米饭小店', '1/1 Thanon Phra Arthit, Phra Nakhon', 'Phra Arthit'),
    ('Nai Mong Hoy Tod', '百年海鲜煎蚝煎饼', '79/7-8 Maha Chai Rd, Samran Rat', 'Samran Rat'),
    ('Pee Aor Tom Yum Kung Noodle', '浓郁冬阴功大虾汤面', '68/8 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Chote Chitr', '历史悠久泰式热菜馆', '146 Phraeng Phuton Rd, Phra Nakhon', 'Phra Nakhon'),
    ('Somboon Seafood', '知名海鲜咖喱蟹连锁', '895/9-10 Rama IV Rd, Silom', 'Silom'),
    ('Suda Restaurant', '口碑泰国当地美食餐厅', '7/1 Rama IV Rd, Silom', 'Silom'),
    ('Baan Phad Thai', '泰式炒河粉经典老店', '68 Soi Phra Athit 44, Phra Nakhon', 'Phra Nakhon'),
    ('Ka Nom Jeen Pa Lek', '老牌泰式米粉与咖喱', '5/1 Soi Phra Sumen 1, Phra Nakhon', 'Phra Nakhon'),
    ('Khao Gaeng Rang Nam', '知名泰式快餐米饭档', '409 Rang Nam Rd, Phaya Thai', 'Phaya Thai'),
    ('Soei', '米其林推荐泰式精致小馆', '101/1 Soi Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Go Ang Pratunam', '米其林必比登船面', '100/1 Soi Petchaburi 19, Pratunam', 'Pratunam'),
    ('Soi Polo Fried Chicken', '炸鸡与辣酱热门快餐', '253 Sukhumvit 21, Asoke', 'Asoke'),
    ('Ann Guay Tiew Kua Gai', '泰式鸡肉炒面风味', '31 Soi Ari 1, Ari', 'Ari'),
    ('Pa Tong Ko', '经典油条与甜品摊', 'Soi Mahadlekluang 2, Pathum Wan', 'Pathum Wan'),
    ('Wattanapanich Seafood', '本地人推荐海鲜餐厅', '152 Rama IV Rd, Silom', 'Silom'),
    ('Khao Gaeng Manee', '家庭式泰式快餐米饭', '23 Sukhumvit 53, Phra Khanong', 'Phra Khanong'),
    ('The Local by Oamthong Thai Cuisine', '传统泰式料理与乡土风味', '718 Saladaeng Rd, Silom', 'Silom'),
    ('Supanniga Eating Room', '米其林推荐泰式家常菜', '160/11 Sukhumvit 55, Thonglor', 'Thonglor'),
    ('Khao', '泰式面点与创新小吃', '18 Sukhumvit 53, Phra Khanong', 'Phra Khanong'),
    ('Baan Matum', '泰式长桌风味街头小馆', '28 Sukhumvit 53, Phra Khanong', 'Phra Khanong'),
    ('Spice Market', '河畔泰式自助与海鲜料理', '190/1 Charoenkrung Rd, Charoenkrung', 'Charoenkrung'),
    ('Ayutthaya Boat Noodles', '经典泰式船面老店', '5/1 Phra Arthit Rd, Phra Nakhon', 'Phra Arthit'),
]
area_centers = {
    'Lumpini': (13.7301, 100.5380),
    'Chong Nonsi': (13.7230, 100.5340),
    'Silom': (13.7260, 100.5430),
    'Sathorn': (13.7235, 100.5380),
    'Sukhumvit 26': (13.7350, 100.5630),
    'Phra Khanong': (13.7315, 100.5845),
    'Thonglor': (13.7390, 100.5830),
    'Sukhumvit 23': (13.7325, 100.5500),
    'Riverside': (13.7190, 100.5145),
    'Charoenkrung': (13.7225, 100.5050),
    'Chinatown': (13.7385, 100.5100),
    'Asoke': (13.7370, 100.5600),
    'Suan Phlu': (13.7275, 100.5340),
    'Ploenchit': (13.7495, 100.5440),
    'Phrom Phong': (13.7368, 100.5660),
    'Siam Square': (13.7460, 100.5330),
    'Ari': (13.7864, 100.5451),
    'Soi 21': (13.7382, 100.5694),
    'Langsuan': (13.7446, 100.5441),
    'Pathum Wan': (13.7492, 100.5347),
    'Phra Arthit': (13.7643, 100.4948),
    'Phra Nakhon': (13.7566, 100.4990),
    'Rama IV': (13.7326, 100.5305),
    'Phaya Thai': (13.7686, 100.5498),
    'Pratunam': (13.7492, 100.5390),
}

random.seed(42)
data = []
for idx, (name, short, address, area) in enumerate(entries, start=1):
    base = area_centers.get(area, (13.7500, 100.5400))
    rnd = random.Random(name)
    lat = round(base[0] + rnd.uniform(-0.0055, 0.0055), 6)
    lng = round(base[1] + rnd.uniform(-0.0085, 0.0085), 6)
    data.append({
        'id': idx,
        'name': name,
        'short': short,
        'address': address,
        'lat': lat,
        'lng': lng,
    })
with open('src/data/places.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
with open('preview.html', 'r', encoding='utf-8') as f:
    text = f.read()
new_block = 'const defaultPlaces = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n'
text, subs = re.subn(r'const defaultPlaces = \[.*?\]\s*;?', new_block, text, flags=re.S)
if subs != 1:
    raise RuntimeError('replacement failed: ' + str(subs))
with open('preview.html', 'w', encoding='utf-8') as f:
    f.write(text)
print('wrote', len(data), 'places')
